//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package doom5.batchutils.config;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="implementationsPackage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="dbConfiguration" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="connectionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="driverClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="connectionString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="onConnectStatement" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                   <element name="prop" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             <element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="properties" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="batchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="prop" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             <element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "implementationsPackage",
    "dbConfiguration",
    "properties"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(required = true)
    protected String implementationsPackage;
    @XmlElement(required = true)
    protected List<Configuration.DbConfiguration> dbConfiguration;
    @XmlElement(required = true)
    protected List<Configuration.Properties> properties;

    /**
     * Gets the value of the implementationsPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementationsPackage() {
        return implementationsPackage;
    }

    /**
     * Sets the value of the implementationsPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementationsPackage(String value) {
        this.implementationsPackage = value;
    }

    /**
     * Gets the value of the dbConfiguration property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dbConfiguration property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDbConfiguration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Configuration.DbConfiguration }
     * </p>
     * 
     * 
     * @return
     *     The value of the dbConfiguration property.
     */
    public List<Configuration.DbConfiguration> getDbConfiguration() {
        if (dbConfiguration == null) {
            dbConfiguration = new ArrayList<>();
        }
        return this.dbConfiguration;
    }

    /**
     * Gets the value of the properties property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the properties property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Configuration.Properties }
     * </p>
     * 
     * 
     * @return
     *     The value of the properties property.
     */
    public List<Configuration.Properties> getProperties() {
        if (properties == null) {
            properties = new ArrayList<>();
        }
        return this.properties;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="connectionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="driverClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="connectionString" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="onConnectStatement" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *         <element name="prop" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   <element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "connectionType",
        "driverClass",
        "connectionString",
        "onConnectStatement",
        "prop"
    })
    public static class DbConfiguration {

        @XmlElement(required = true)
        protected String connectionType;
        @XmlElement(required = true)
        protected String driverClass;
        @XmlElement(required = true)
        protected String connectionString;
        @XmlElement(required = true)
        protected List<String> onConnectStatement;
        @XmlElement(required = true)
        protected List<Configuration.DbConfiguration.Prop> prop;

        /**
         * Gets the value of the connectionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConnectionType() {
            return connectionType;
        }

        /**
         * Sets the value of the connectionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConnectionType(String value) {
            this.connectionType = value;
        }

        /**
         * Gets the value of the driverClass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDriverClass() {
            return driverClass;
        }

        /**
         * Sets the value of the driverClass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDriverClass(String value) {
            this.driverClass = value;
        }

        /**
         * Gets the value of the connectionString property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConnectionString() {
            return connectionString;
        }

        /**
         * Sets the value of the connectionString property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConnectionString(String value) {
            this.connectionString = value;
        }

        /**
         * Gets the value of the onConnectStatement property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the onConnectStatement property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getOnConnectStatement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * </p>
         * 
         * 
         * @return
         *     The value of the onConnectStatement property.
         */
        public List<String> getOnConnectStatement() {
            if (onConnectStatement == null) {
                onConnectStatement = new ArrayList<>();
            }
            return this.onConnectStatement;
        }

        /**
         * Gets the value of the prop property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the prop property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getProp().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.DbConfiguration.Prop }
         * </p>
         * 
         * 
         * @return
         *     The value of the prop property.
         */
        public List<Configuration.DbConfiguration.Prop> getProp() {
            if (prop == null) {
                prop = new ArrayList<>();
            }
            return this.prop;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         <element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "value"
        })
        public static class Prop {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String value;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

			@Override
			public String toString() {
				return "Prop [name=" + name + ", value=" + value + "]";
			}

        }


		@Override
		public String toString() {
			return "DbConfiguration [connectionType=" + connectionType + ", driverClass=" + driverClass
					+ ", connectionString=" + connectionString + ", onConnectStatement=" + onConnectStatement
					+ ", prop=" + prop + "]";
		}

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="batchName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="prop" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   <element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "batchName",
        "prop"
    })
    public static class Properties {

        @XmlElement(required = true)
        protected String batchName;
        @XmlElement(required = true)
        protected List<Configuration.Properties.Prop> prop;

        /**
         * Gets the value of the batchName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBatchName() {
            return batchName;
        }

        /**
         * Sets the value of the batchName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBatchName(String value) {
            this.batchName = value;
        }

        /**
         * Gets the value of the prop property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the prop property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getProp().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Properties.Prop }
         * </p>
         * 
         * 
         * @return
         *     The value of the prop property.
         */
        public List<Configuration.Properties.Prop> getProp() {
            if (prop == null) {
                prop = new ArrayList<>();
            }
            return this.prop;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         <element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "value"
        })
        public static class Prop {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String value;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

			@Override
			public String toString() {
				return "Prop [name=" + name + ", value=" + value + "]";
			}

        }


		@Override
		public String toString() {
			return "Properties [batchName=" + batchName + ", prop=" + prop + "]";
		}

    }


	@Override
	public String toString() {
		return "Configuration [implementationsPackage=" + implementationsPackage + ", dbConfiguration="
				+ dbConfiguration + ", properties=" + properties + "]";
	}

}
