//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package doom5.batchutils.config;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the doom5.batchutils.config package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: doom5.batchutils.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     * @return
     *     the new instance of {@link Configuration }
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Configuration.Properties }
     * 
     * @return
     *     the new instance of {@link Configuration.Properties }
     */
    public Configuration.Properties createConfigurationProperties() {
        return new Configuration.Properties();
    }

    /**
     * Create an instance of {@link Configuration.DbConfiguration }
     * 
     * @return
     *     the new instance of {@link Configuration.DbConfiguration }
     */
    public Configuration.DbConfiguration createConfigurationDbConfiguration() {
        return new Configuration.DbConfiguration();
    }

    /**
     * Create an instance of {@link Configuration.Properties.Prop }
     * 
     * @return
     *     the new instance of {@link Configuration.Properties.Prop }
     */
    public Configuration.Properties.Prop createConfigurationPropertiesProp() {
        return new Configuration.Properties.Prop();
    }

    /**
     * Create an instance of {@link Configuration.DbConfiguration.Prop }
     * 
     * @return
     *     the new instance of {@link Configuration.DbConfiguration.Prop }
     */
    public Configuration.DbConfiguration.Prop createConfigurationDbConfigurationProp() {
        return new Configuration.DbConfiguration.Prop();
    }

}
